<?php
//============================================================+
// Include the main TCPDF library (search for installation path).
//require_once('tcpdf.php');
require_once($_SERVER['DOCUMENT_ROOT'] . "/includes/functions.php");
// require_once($_SERVER['DOCUMENT_ROOT'] . "/tcpdf/config/tcpdf_config.php");
require_once($_SERVER['DOCUMENT_ROOT'] . "/tcpdf/tcpdf.php");
//
//Create Session
$SESSION = new ClassSession();
$UTIL = new ClassUtil($SESSION);

if (!isset($_SESSION)) { 
    session_start();
}
$_SESSION['error_type'] = '';


$post_parameters = "";

$option_filter = "opt_general_data"; 
if (!empty($_REQUEST['option_filter'])) $option_filter = $_REQUEST['option_filter']; 

$test_id = 0;
if (!empty($_REQUEST['test_id'])) $test_id = $_REQUEST['test_id'];
$post_parameters .= "&test_id=" . $test_id;
//
if (!empty($_REQUEST['id_customer'])) $id_customer .= "&id_customer=" .$_REQUEST['id_customer'];
//
if (!empty($_REQUEST['vehicle'])) $post_parameters .= "&vehicle=" .$_REQUEST['vehicle'];
if (($_REQUEST['status'] != '') && ($_REQUEST['status'] != '-1')) $post_parameters .= "&status=" .$_REQUEST['status'];
if (!empty($_REQUEST['plate'])) $post_parameters .= "&plate=" .$_REQUEST['plate'];
//if (!empty($_REQUEST['id_shop_system'])) $post_parameters .= "&id_shop_system=" .$_REQUEST['id_shop_system'];
//
$arr_id_shop_system = array();
if (!empty($_REQUEST['id_shop_system'])) {
    $arr_id_shop_system = $_REQUEST['id_shop_system'];
}

if (!empty($arr_id_shop_system)) {
    for ($i = 0; $i < count($arr_id_shop_system); $i++) {
        $post_parameters .= "&id_shop_system[" . $i . "]=" . $arr_id_shop_system[$i];
    }
} // end if isset($arr_id_shop_system);

$xml = REST_POST("/api/xml/v1/vehicle_tests_list.php", $post_parameters,null, false, false);
//echo $xml;
// print_r($xml);
    
// echo $post_parameters;
// die('AAA');

$records_cnt = 0;

$xml_obj = simplexml_load_string($xml);
if ($xml_obj == NULL) {
} else {
    $objVehicle_Tests = $xml_obj->vehicle_tests_list->vehicle_tests;
    $records_cnt = count($objVehicle_Tests);
}

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
/*DKB***/
$HEADER_TITLE = '';
$HEADER_STRING = '';

$HEADER_TITLE = 'AUTO Diagnostic Office';
$HEADER_STRING = 'www.derrickbasoah.com';

$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor($HEADER_TITLE);
$pdf->SetTitle('International Postal Service');
$pdf->SetSubject('Products');
$pdf->SetKeywords('Angebot, PDF, Postal, Shipment, offer, Products, Produkt');


// set default header data
//$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, $HEADER_TITLE, $HEADER_STRING);


// set header and footer fonts
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', '', 9);

// add a page
$pdf->AddPage();
//$pdf->writeHTML($post_parameters, true, false, true, false, '');

// Set some hearder content to print
$html = '<div>
                <table>
                    <tr>
                        <td width="80%" align="left">
                            <span><strong>Generated by:</strong> ' . $_SESSION['fullname'] . '</span><br>
                            <span><strong>Date: </strong>' . substr(date("d.m.Y H:i:s"), 0, 16)  . '</span><br><br>';
$html .= '          </td>

                        <td width="20%" align="right">';
$html .= '              <img src="/images/auto_logo.png"  width="150">';
$html .= '          </td>
                    </tr>
                </table>
            </div>';

$pdf->writeHTML($html, true, false, true, false, '');
//
$iRowColor = 0; $table_bg_color = ""; $status_str = "";
//
//  opt_stock_data opt_detail_data opt_barcode
if ($option_filter == 'opt_general_data') {  
    $html =  '<h3>Vehicle Test Overview: <em style="font-size: smaller; color: #CACACF;">General</em></h3>';
    $html .= '<div>
                    <table cellpadding="2" style="border-bottom: 2px solid #607D8B;">
                        <tr>';
    $html .= '          <th width="5%" style="border-bottom: 1px solid #607D8B;" align="left"><b>ID</b></th>
                            <th width="25%" style="border-bottom: 1px solid #607D8B;" align="left"><b><span>Vehicle</span><br>Plate</b></th> 
                            <th width="35%" style="border-bottom: 1px solid #607D8B;" align="left"><b>Customer</b></th>
                            <th width="20%" style="border-bottom: 1px solid #607D8B;" align="left"><b>Date<br>Operator</b></th>
                            <th width="15%" style="border-bottom: 1px solid #607D8B;" align="left"><b>Status</b></th>
                        </tr>';
    if (!empty($objVehicle_Tests)) {
        foreach ($objVehicle_Tests as $Vehicle_Tests) {
            ((++$iRowColor % 2) == 0) ? $table_bg_color = $UTIL->table_bg_color_odd() : $table_bg_color = $UTIL->table_bg_color_even();

            $html .= '<tr bgcolor="' . $table_bg_color . '">
                        <td>' . $Vehicle_Tests->test_id . '</td>
                        <td>' . utf8_decode($Vehicle_Tests->vehicle) . '<br><span style="color: #8A8A8B;">' . utf8_decode($Vehicle_Tests->plate) . '</span></td>
                        <td>' . utf8_decode($Vehicle_Tests->customer_company) . ' ( ' . $Vehicle_Tests->id_customer . ' )</td>
                        <td>' . date('d-m-Y', intval($Vehicle_Tests->date)) . '<br><span style="color: #8A8A8B;">' . DB_UserFullName($Vehicle_Tests->id_users_created_by) . '</span></td>
                        <td><b>' . Get_Status($Vehicle_Tests->status) . '</b></td>
                    </tr>';

            $html .= '<tr bgcolor="' . $table_bg_color . '">
                        <td colspan="5" style="border-top: 1px dashed #607D8B; font-size: small;">';
                            $html .= '<p style="font-style: italic; margin-bottom: 0px;">services to provide on vehicle:</p>';
                        
                            if ($Vehicle_Tests->flag_brakes == 1) $html .= '<span>'. $UTIL->IMG_Activated(5, 5) .' Brakes </span>';
                            if ($Vehicle_Tests->flag_suspension_side_slip == 1) $html .= '<span>'. $UTIL->IMG_Activated(5, 5) .' Suspension / Side Slip </span>';
                            if ($Vehicle_Tests->flag_headlight == 1) $html .= '<span>'. $UTIL->IMG_Activated(5, 5) .' Headlight </span>';
                            if ($Vehicle_Tests->flag_alignment == 1) $html .= '<span>'. $UTIL->IMG_Activated(5, 5) .' Alignment </span>';
                            if ($Vehicle_Tests->flag_vulcanize == 1) $html .= '<span>'. $UTIL->IMG_Activated(5, 5) .' Vulcanize </span>';
                            if ($Vehicle_Tests->flag_visual_defects == 1) $html .= '<span>'. $UTIL->IMG_Activated(5, 5) .' Visual Defects </span>';
            $html .= '  </td>
                    </tr>';

        } // end foreach ($objVehicle_Tests as $Vehicle_Tests);
    }// end if (!empty($objVehicle_Tests));

} elseif ($option_filter == 'opt_detail_data') { 
    $html =  '<h3>Vehicle Test Overview: <em style="font-size: smaller; color: #CACACF;">Detail</em></h3>';
    $html .= '<div>
                    <table cellpadding="2" style="border-bottom: 2px solid #607D8B;">
                        <tr>';
    $html .= '          <th width="5%" style="border-bottom: 1px solid #607D8B;" align="left"><b>ID</b></th>
                            <th width="25%" style="border-bottom: 1px solid #607D8B;" align="left"><b><span>Vehicle</span><br>Plate</b></th> 
                            <th width="35%" style="border-bottom: 1px solid #607D8B;" align="left"><b>Customer</b></th>
                            <th width="20%" style="border-bottom: 1px solid #607D8B;" align="left"><b>Date<br>Operator</b></th>
                            <th width="15%" style="border-bottom: 1px solid #607D8B;" align="left"><b>Status</b></th>
                        </tr>';
    if (!empty($objVehicle_Tests)) {
        foreach ($objVehicle_Tests as $Vehicle_Tests) {
            ((++$iRowColor % 2) == 0) ? $table_bg_color = $UTIL->table_bg_color_odd() : $table_bg_color = $UTIL->table_bg_color_even();

            $html .= '<tr bgcolor="' . $table_bg_color . '">
                        <td>' . $Vehicle_Tests->test_id . '</td>
                        <td>' . utf8_decode($Vehicle_Tests->vehicle) . '<br><span style="color: #8A8A8B;">' . utf8_decode($Vehicle_Tests->plate) . '</span></td>
                        <td>' . utf8_decode($Vehicle_Tests->customer_company) . ' ( ' . $Vehicle_Tests->id_customer . ' )</td>
                        <td>' . date('d-m-Y', intval($Vehicle_Tests->date)) . '<br><span style="color: #8A8A8B;">' . DB_UserFullName($Vehicle_Tests->id_users_created_by) . '</span></td>
                        <td><b>' . Get_Status($Vehicle_Tests->status) . '</b></td>
                    </tr>';

            // $html .= '<tr bgcolor="' . $table_bg_color . '">
            //             <p>Nice</p>
            //         </tr>';

        } // end foreach ($objVehicle_Tests as $Vehicle_Tests);
    }// end if (!empty($objVehicle_Tests));
}

    $html .= '  </table>
                </div>
                <p style="font-size: 10rem;"><strong>No. of Records: </strong>' . $records_cnt . '</p>
                <br><br><br>';



$pdf->writeHTML($html, true, false, true, false, '');
// add a page
//$pdf->AddPage();

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// reset pointer to the last page
$pdf->lastPage();


// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
$pdf->Output('Vehicle_Test_Overview.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+
?>